
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_CipherSuite__
#define __gnu_javax_net_ssl_provider_CipherSuite__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace mac
        {
            class IMac;
        }
        namespace mode
        {
            class IMode;
        }
      }
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class CipherSuite;
              class ProtocolVersion;
          }
        }
      }
    }
  }
  namespace javax
  {
    namespace crypto
    {
        class Cipher;
        class Mac;
    }
  }
}

class gnu::javax::net::ssl::provider::CipherSuite : public ::java::lang::Object
{

  CipherSuite(::java::lang::String *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *, jint, jint, jint, ::java::lang::String *, ::gnu::javax::net::ssl::provider::ProtocolVersion *);
  CipherSuite(JArray< jbyte > *);
public: // actually package-private
  static ::gnu::javax::net::ssl::provider::CipherSuite * forName(::java::lang::String *);
  static ::java::util::List * availableSuiteNames();
  static ::gnu::javax::net::ssl::provider::CipherSuite * read(::java::io::InputStream *);
  static ::gnu::javax::crypto::mode::IMode * getCipher(::java::lang::String *);
  static ::javax::crypto::Cipher * getJCECipher(::java::lang::String *);
  static ::gnu::javax::crypto::mac::IMac * getMac(::java::lang::String *);
  static ::javax::crypto::Mac * getJCEMac(::java::lang::String *);
public:
  void write(::java::io::OutputStream *);
public: // actually package-private
  ::gnu::javax::net::ssl::provider::CipherSuite * resolve(::gnu::javax::net::ssl::provider::ProtocolVersion *);
  ::java::lang::String * getCipher();
  jint getKeyLength();
  ::java::lang::String * getKeyExchange();
  ::java::lang::String * getSignature();
  ::java::lang::String * getMac();
  jboolean isExportable();
  jboolean isStreamCipher();
  ::java::lang::String * getAuthType();
  JArray< jbyte > * getId();
  ::gnu::javax::net::ssl::provider::ProtocolVersion * getVersion();
public:
  jboolean equals(::java::lang::Object *);
  jint hashCode();
  ::java::lang::String * toString();
private:
  static ::java::util::List * tlsSuiteNames;
  static ::java::util::HashMap * namesToSuites;
public: // actually package-private
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_NULL_WITH_NULL_NULL;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_NULL_MD5;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_NULL_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_EXPORT_WITH_RC4_40_MD5;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_RC4_128_MD5;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_RC4_128_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_DSS_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_RSA_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_DSS_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_RSA_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_DSS_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DH_RSA_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_CAST_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_CAST_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_3DES_EDE_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_AES_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_DSS_WITH_AES_256_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_CAST_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_CAST_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_3DES_EDE_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_AES_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_DHE_RSA_WITH_AES_256_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_CAST_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_CAST_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_3DES_EDE_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_AES_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * SSL_RSA_WITH_AES_256_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_NULL_WITH_NULL_NULL;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_NULL_MD5;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_NULL_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_EXPORT_WITH_RC4_40_MD5;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_RC4_128_MD5;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_RC4_128_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_DSS_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_RSA_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_DES_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_DSS_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_RSA_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_DSS_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DH_RSA_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_CAST_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_CAST_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_3DES_EDE_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_AES_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_DSS_WITH_AES_256_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_CAST_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_CAST_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_3DES_EDE_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_AES_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_DHE_RSA_WITH_AES_256_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_CAST_128_CBC_SHA;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_CAST_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_3DES_EDE_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_AES_128_CBC_RMD;
  static ::gnu::javax::net::ssl::provider::CipherSuite * TLS_RSA_WITH_AES_256_CBC_RMD;
private:
  ::java::lang::String * __attribute__((aligned(__alignof__( ::java::lang::Object)))) cipherName;
  ::java::lang::String * kexName;
  ::java::lang::String * sigName;
  ::java::lang::String * macName;
  jboolean exportable;
  jboolean isStream;
  jint keyLength;
  JArray< jbyte > * id;
  ::java::lang::String * name;
  ::gnu::javax::net::ssl::provider::ProtocolVersion * version;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_CipherSuite__
