
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_ClientHello__
#define __gnu_javax_net_ssl_provider_ClientHello__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class ClientHello;
              class ProtocolVersion;
              class Random;
          }
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::ClientHello : public ::java::lang::Object
{

public: // actually package-private
  ClientHello(::gnu::javax::net::ssl::provider::ProtocolVersion *, ::gnu::javax::net::ssl::provider::Random *, JArray< jbyte > *, ::java::util::List *, ::java::util::List *);
  ClientHello(::gnu::javax::net::ssl::provider::ProtocolVersion *, ::gnu::javax::net::ssl::provider::Random *, JArray< jbyte > *, ::java::util::List *, ::java::util::List *, ::java::util::List *);
  static ::gnu::javax::net::ssl::provider::ClientHello * read(::java::io::InputStream *);
public:
  void write(::java::io::OutputStream *);
public: // actually package-private
  ::gnu::javax::net::ssl::provider::ProtocolVersion * getVersion();
  ::gnu::javax::net::ssl::provider::Random * getRandom();
  JArray< jbyte > * getSessionId();
  ::java::util::List * getCipherSuites();
  ::java::util::List * getCompressionMethods();
  ::java::util::List * getExtensions();
public:
  ::java::lang::String * toString();
private:
  ::gnu::javax::net::ssl::provider::ProtocolVersion * __attribute__((aligned(__alignof__( ::java::lang::Object)))) version;
  ::gnu::javax::net::ssl::provider::Random * random;
  JArray< jbyte > * sessionId;
  ::java::util::List * suites;
  ::java::util::List * comp;
  ::java::util::List * extensions;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_ClientHello__
