
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_Extension__
#define __gnu_javax_net_ssl_provider_Extension__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class Extension;
              class Extension$Type;
          }
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::Extension : public ::java::lang::Object
{

public: // actually package-private
  Extension(::gnu::javax::net::ssl::provider::Extension$Type *, JArray< jbyte > *);
  static ::gnu::javax::net::ssl::provider::Extension * read(::java::io::InputStream *);
public:
  void write(::java::io::OutputStream *);
public: // actually package-private
  ::gnu::javax::net::ssl::provider::Extension$Type * getType();
  JArray< jbyte > * getValue();
public:
  ::java::lang::String * toString();
private:
  ::gnu::javax::net::ssl::provider::Extension$Type * __attribute__((aligned(__alignof__( ::java::lang::Object)))) type;
  JArray< jbyte > * value;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_Extension__
