
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_Extension$Type__
#define __gnu_javax_net_ssl_provider_Extension$Type__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class Extension$Type;
          }
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::Extension$Type : public ::java::lang::Object
{

  Extension$Type(jint);
public: // actually package-private
  static ::gnu::javax::net::ssl::provider::Extension$Type * read(::java::io::InputStream *);
public:
  JArray< jbyte > * getEncoded();
  jint getValue();
  ::java::lang::String * toString();
public: // actually package-private
  static ::gnu::javax::net::ssl::provider::Extension$Type * SERVER_NAME;
  static ::gnu::javax::net::ssl::provider::Extension$Type * MAX_FRAGMENT_LENGTH;
  static ::gnu::javax::net::ssl::provider::Extension$Type * CLIENT_CERTIFICATE_URL;
  static ::gnu::javax::net::ssl::provider::Extension$Type * TRUSTED_CA_KEYS;
  static ::gnu::javax::net::ssl::provider::Extension$Type * TRUNCATED_HMAC;
  static ::gnu::javax::net::ssl::provider::Extension$Type * STATUS_REQUEST;
  static ::gnu::javax::net::ssl::provider::Extension$Type * SRP;
  static ::gnu::javax::net::ssl::provider::Extension$Type * CERT_TYPE;
private:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object)))) value;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_Extension$Type__
