
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_awt_peer_swing_SwingContainerPeer__
#define __gnu_java_awt_peer_swing_SwingContainerPeer__

#pragma interface

#include <gnu/java/awt/peer/swing/SwingComponentPeer.h>
extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace awt
      {
        namespace peer
        {
          namespace swing
          {
              class SwingContainerPeer;
          }
        }
      }
    }
  }
  namespace java
  {
    namespace awt
    {
        class Component;
        class Graphics;
        class Insets;
      namespace event
      {
          class MouseEvent;
      }
    }
  }
}

class gnu::java::awt::peer::swing::SwingContainerPeer : public ::gnu::java::awt::peer::swing::SwingComponentPeer
{

public:
  SwingContainerPeer(::java::awt::Component *);
  virtual ::java::awt::Insets * insets();
  virtual ::java::awt::Insets * getInsets();
  virtual void beginValidate();
  virtual void endValidate();
  virtual void beginLayout();
  virtual void endLayout();
  virtual jboolean isPaintPending();
  virtual jboolean isRestackSupported();
  virtual void cancelPendingPaint(jint, jint, jint, jint);
  virtual void restack();
public: // actually protected
  virtual void peerPaint(::java::awt::Graphics *);
  virtual void handleMouseEvent(::java::awt::event::MouseEvent *);
  virtual void handleMouseMotionEvent(::java::awt::event::MouseEvent *);
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_java_awt_peer_swing_SwingContainerPeer__
