
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_Alert__
#define __gnu_javax_net_ssl_provider_Alert__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class Alert;
              class Alert$Description;
              class Alert$Level;
          }
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::Alert : public ::java::lang::Object
{

public: // actually package-private
  Alert(::gnu::javax::net::ssl::provider::Alert$Level *, ::gnu::javax::net::ssl::provider::Alert$Description *);
  static ::gnu::javax::net::ssl::provider::Alert * read(::java::io::InputStream *);
  static ::gnu::javax::net::ssl::provider::Alert * forName(::java::lang::String *);
public:
  void write(::java::io::OutputStream *);
public: // actually package-private
  JArray< jbyte > * getEncoded();
  ::gnu::javax::net::ssl::provider::Alert$Level * getLevel();
  ::gnu::javax::net::ssl::provider::Alert$Description * getDescription();
public:
  ::java::lang::String * toString();
private:
  ::gnu::javax::net::ssl::provider::Alert$Level * __attribute__((aligned(__alignof__( ::java::lang::Object)))) level;
  ::gnu::javax::net::ssl::provider::Alert$Description * description;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_Alert__
