
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_Finished__
#define __gnu_javax_net_ssl_provider_Finished__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class CipherSuite;
              class Finished;
          }
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::Finished : public ::java::lang::Object
{

public: // actually package-private
  Finished(JArray< jbyte > *);
  Finished(JArray< jbyte > *, JArray< jbyte > *);
  static ::gnu::javax::net::ssl::provider::Finished * read(::java::io::InputStream *, ::gnu::javax::net::ssl::provider::CipherSuite *);
public:
  void write(::java::io::OutputStream *);
public: // actually package-private
  JArray< jbyte > * getVerifyData();
  JArray< jbyte > * getMD5Hash();
  JArray< jbyte > * getSHAHash();
public:
  ::java::lang::String * toString();
private:
  JArray< jbyte > * __attribute__((aligned(__alignof__( ::java::lang::Object)))) verifyData;
  JArray< jbyte > * md5;
  JArray< jbyte > * sha;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_Finished__
