
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_Handshake$Body__
#define __gnu_javax_net_ssl_provider_Handshake$Body__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class Handshake$Body;
          }
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::Handshake$Body : public ::java::lang::Object
{

public:
  virtual void write(::java::io::OutputStream *) = 0;
  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif // __gnu_javax_net_ssl_provider_Handshake$Body__
