
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_ProtocolVersion__
#define __gnu_javax_net_ssl_provider_ProtocolVersion__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class ProtocolVersion;
          }
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::ProtocolVersion : public ::java::lang::Object
{

  ProtocolVersion(jint, jint);
public: // actually package-private
  static ::gnu::javax::net::ssl::provider::ProtocolVersion * read(::java::io::InputStream *);
  static ::gnu::javax::net::ssl::provider::ProtocolVersion * getInstance(jint, jint);
public:
  void write(::java::io::OutputStream *);
public: // actually package-private
  JArray< jbyte > * getEncoded();
  jint getMajor();
  jint getMinor();
public:
  jboolean equals(::java::lang::Object *);
  jint hashCode();
  jint compareTo(::java::lang::Object *);
  ::java::lang::String * toString();
public: // actually package-private
  static ::gnu::javax::net::ssl::provider::ProtocolVersion * SSL_3;
  static ::gnu::javax::net::ssl::provider::ProtocolVersion * TLS_1;
  static ::gnu::javax::net::ssl::provider::ProtocolVersion * TLS_1_1;
private:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object)))) major;
  jint minor;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_ProtocolVersion__
