
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_ServerKeyExchange__
#define __gnu_javax_net_ssl_provider_ServerKeyExchange__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class CipherSuite;
              class ProtocolVersion;
              class ServerKeyExchange;
              class Signature;
          }
        }
      }
    }
  }
  namespace java
  {
    namespace math
    {
        class BigInteger;
    }
    namespace security
    {
        class PublicKey;
    }
  }
}

class gnu::javax::net::ssl::provider::ServerKeyExchange : public ::java::lang::Object
{

public: // actually package-private
  ServerKeyExchange(::java::security::PublicKey *, ::gnu::javax::net::ssl::provider::Signature *);
  ServerKeyExchange(::java::security::PublicKey *, ::gnu::javax::net::ssl::provider::Signature *, JArray< jbyte > *);
  static ::gnu::javax::net::ssl::provider::ServerKeyExchange * read(::java::io::InputStream *, ::gnu::javax::net::ssl::provider::CipherSuite *, ::java::security::PublicKey *);
public:
  virtual void write(::java::io::OutputStream *);
  virtual void write(::java::io::OutputStream *, ::gnu::javax::net::ssl::provider::ProtocolVersion *);
public: // actually package-private
  virtual ::java::security::PublicKey * getPublicKey();
  virtual ::gnu::javax::net::ssl::provider::Signature * getSignature();
  virtual JArray< jbyte > * getSRPSalt();
public:
  virtual ::java::lang::String * toString();
private:
  void writeBigint(::java::io::OutputStream *, ::java::math::BigInteger *);
  ::java::security::PublicKey * __attribute__((aligned(__alignof__( ::java::lang::Object)))) publicKey;
  ::gnu::javax::net::ssl::provider::Signature * signature;
  JArray< jbyte > * srpSalt;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_ServerKeyExchange__
