#! /bin/sh

#
# Download the ecj jar file needed by gcj.
# Run this from the top level of the gcc source tree and the libjava
# build will do the right thing.
#
# (C) 2006 Free Software Foundation
#
# This script is Free Software, and it can be copied, distributed and
# modified as defined in the GNU General Public License.  A copy of
# its license can be downloaded from http://www.gnu.org/copyleft/gpl.html
#

wget -O ecj.jar ftp://sources.redhat.com/pub/java/ecj-latest.jar
