/* Test the `vbslp16' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vbslp16 (void)
{
  poly16x4_t out_poly16x4_t;
  poly16x4_t arg0_poly16x4_t;
  poly16x4_t arg1_poly16x4_t;
  poly16x4_t arg2_poly16x4_t;

  out_poly16x4_t = vbsl_p16 (arg0_poly16x4_t, arg1_poly16x4_t, arg2_poly16x4_t);
}

/* { dg-final { scan-assembler "((vbsl)|(vbit)|(vbif))\[ 	\]+\[dD\]\[0-9\]+, \[dD\]\[0-9\]+, \[dD\]\[0-9\]+!?\(\[ 	\]+@\[a-zA-Z0-9 \]+\)?\n" } } */

