/* Test the `vget_highu8' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vget_highu8 (void)
{
  uint8x8_t out_uint8x8_t;
  uint8x16_t arg0_uint8x16_t;

  out_uint8x8_t = vget_high_u8 (arg0_uint8x16_t);
}


