/* Test the `vreinterprets32_u16' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterprets32_u16 (void)
{
  int32x2_t out_int32x2_t;
  uint16x4_t arg0_uint16x4_t;

  out_int32x2_t = vreinterpret_s32_u16 (arg0_uint16x4_t);
}


