/* Test the `vreinterpretQu32_u64' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretQu32_u64 (void)
{
  uint32x4_t out_uint32x4_t;
  uint64x2_t arg0_uint64x2_t;

  out_uint32x4_t = vreinterpretq_u32_u64 (arg0_uint64x2_t);
}


