/* Test the `vreinterpretu32_s8' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretu32_s8 (void)
{
  uint32x2_t out_uint32x2_t;
  int8x8_t arg0_int8x8_t;

  out_uint32x2_t = vreinterpret_u32_s8 (arg0_int8x8_t);
}


