/* Test the `vreinterpretQu64_u16' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretQu64_u16 (void)
{
  uint64x2_t out_uint64x2_t;
  uint16x8_t arg0_uint16x8_t;

  out_uint64x2_t = vreinterpretq_u64_u16 (arg0_uint16x8_t);
}


