/* Test the `vreinterpretQu32_s8' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretQu32_s8 (void)
{
  uint32x4_t out_uint32x4_t;
  int8x16_t arg0_int8x16_t;

  out_uint32x4_t = vreinterpretq_u32_s8 (arg0_int8x16_t);
}


