/* Test the `vreinterpretQp8_u16' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretQp8_u16 (void)
{
  poly8x16_t out_poly8x16_t;
  uint16x8_t arg0_uint16x8_t;

  out_poly8x16_t = vreinterpretq_p8_u16 (arg0_uint16x8_t);
}


