/* Test the `vreinterpretp8_s64' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm_neon_ok } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */

#include "arm_neon.h"

void test_vreinterpretp8_s64 (void)
{
  poly8x8_t out_poly8x8_t;
  int64x1_t arg0_int64x1_t;

  out_poly8x8_t = vreinterpret_p8_s64 (arg0_int64x1_t);
}


