/* Test the `vreinterprets16_s64' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterprets16_s64 (void)
{
  int16x4_t out_int16x4_t;
  int64x1_t arg0_int64x1_t;

  out_int16x4_t = vreinterpret_s16_s64 (arg0_int64x1_t);
}


