/* Test the `vreinterpretf32_u64' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm_neon_ok } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
#include "arm_neon.h"

void test_vreinterpretf32_u64 (void)
{
  float32x2_t out_float32x2_t;
  uint64x1_t arg0_uint64x1_t;

  out_float32x2_t = vreinterpret_f32_u64 (arg0_uint64x1_t);
}


