/* Test the `vreinterprets32_f32' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm_neon_ok } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */

#include "arm_neon.h"

void test_vreinterprets32_f32 (void)
{
  int32x2_t out_int32x2_t;
  float32x2_t arg0_float32x2_t;

  out_int32x2_t = vreinterpret_s32_f32 (arg0_float32x2_t);
}


