/* Test the `vreinterpretu64_s32' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretu64_s32 (void)
{
  uint64x1_t out_uint64x1_t;
  int32x2_t arg0_int32x2_t;

  out_uint64x1_t = vreinterpret_u64_s32 (arg0_int32x2_t);
}


