/* Test the `vreinterprets32_s64' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm_neon_ok } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
#include "arm_neon.h"

void test_vreinterprets32_s64 (void)
{
  int32x2_t out_int32x2_t;
  int64x1_t arg0_int64x1_t;

  out_int32x2_t = vreinterpret_s32_s64 (arg0_int64x1_t);
}


