/* Test the `vreinterpretf32_u32' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretf32_u32 (void)
{
  float32x2_t out_float32x2_t;
  uint32x2_t arg0_uint32x2_t;

  out_float32x2_t = vreinterpret_f32_u32 (arg0_uint32x2_t);
}


