/* Test the `vreinterpretf32_s16' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretf32_s16 (void)
{
  float32x2_t out_float32x2_t;
  int16x4_t arg0_int16x4_t;

  out_float32x2_t = vreinterpret_f32_s16 (arg0_int16x4_t);
}


