/* Test the `vreinterpretu8_u64' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vreinterpretu8_u64 (void)
{
  uint8x8_t out_uint8x8_t;
  uint64x1_t arg0_uint64x1_t;

  out_uint8x8_t = vreinterpret_u8_u64 (arg0_uint64x1_t);
}


