/* Test the `vreinterpretu8_f32' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm_neon_ok } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
#include "arm_neon.h"

void test_vreinterpretu8_f32 (void)
{
  uint8x8_t out_uint8x8_t;
  float32x2_t arg0_float32x2_t;

  out_uint8x8_t = vreinterpret_u8_f32 (arg0_float32x2_t);
}


