/* Test the `vreinterpretQs8_f32' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm_neon_ok } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */

#include "arm_neon.h"

void test_vreinterpretQs8_f32 (void)
{
  int8x16_t out_int8x16_t;
  float32x4_t arg0_float32x4_t;

  out_int8x16_t = vreinterpretq_s8_f32 (arg0_float32x4_t);
}


