/* Test the `vreinterpretu64_f32' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm_neon_ok } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
#include "arm_neon.h"

void test_vreinterpretu64_f32 (void)
{
  uint64x1_t out_uint64x1_t;
  float32x2_t arg0_float32x2_t;

  out_uint64x1_t = vreinterpret_u64_f32 (arg0_float32x2_t);
}


