/* Test the `vst4Q_lanep16' ARM Neon intrinsic.  */
/* This file was autogenerated by neon-testgen.  */

/* { dg-do compile } */
/* { dg-require-effective-target arm32 } */
/* { dg-options "-O0 -mfpu=neon -mfloat-abi=softfp" } */
/* { dg-skip-if "" { *-*-* } { "-mcpu=iwmmxt" "-march=iwmmxt" } { "" } } */

#include "arm_neon.h"

void test_vst4Q_lanep16 (void)
{
  poly16_t *arg0_poly16_t;
  poly16x8x4_t arg1_poly16x8x4_t;

  vst4q_lane_p16 (arg0_poly16_t, arg1_poly16x8x4_t, 0);
}

/* { dg-final { scan-assembler "vst4\.16\[ 	\]+\\\{((\[dD\]\[0-9\]+\\\[0\\\]-\[dD\]\[0-9\]+\\\[0\\\])|(\[dD\]\[0-9\]+\\\[0\\\], \[dD\]\[0-9\]+\\\[0\\\], \[dD\]\[0-9\]+\\\[0\\\], \[dD\]\[0-9\]+\\\[0\\\]))\\\}, \\\[\[rR\]\[0-9\]+\\\]!?\(\[ 	\]+@\[a-zA-Z0-9 \]+\)?\n" } } */

