
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_html_StyleSheet$ListPainter__
#define __javax_swing_text_html_StyleSheet$ListPainter__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace java
  {
    namespace awt
    {
        class Graphics;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
          class AttributeSet;
          class View;
        namespace html
        {
            class StyleSheet$ListPainter;
        }
      }
    }
  }
}

class javax::swing::text::html::StyleSheet$ListPainter : public ::java::lang::Object
{

public: // actually package-private
  StyleSheet$ListPainter(::javax::swing::text::AttributeSet *);
public:
  virtual void paint(::java::awt::Graphics *, jfloat, jfloat, jfloat, jfloat, ::javax::swing::text::View *, jint);
public: // actually package-private
  ::javax::swing::text::AttributeSet * __attribute__((aligned(__alignof__( ::java::lang::Object)))) as;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_swing_text_html_StyleSheet$ListPainter__
