
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_html_TableView$RowView__
#define __javax_swing_text_html_TableView$RowView__

#pragma interface

#include <javax/swing/text/TableView$TableRow.h>
extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
          class Element;
        namespace html
        {
            class StyleSheet;
            class TableView;
            class TableView$RowView;
        }
      }
    }
  }
}

class javax::swing::text::html::TableView$RowView : public ::javax::swing::text::TableView$TableRow
{

public:
  TableView$RowView(::javax::swing::text::html::TableView *, ::javax::swing::text::Element *);
public: // actually protected
  virtual ::javax::swing::text::html::StyleSheet * getStyleSheet();
public: // actually package-private
  ::javax::swing::text::html::TableView * __attribute__((aligned(__alignof__( ::javax::swing::text::TableView$TableRow)))) this$0;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_swing_text_html_TableView$RowView__
