# 981006-1
# For MIPS at least, pic is needed to trigger the problem.
dg-init
if { [istarget rs6000-*-aix*]
     || [istarget powerpc*-*-aix*]
     || [istarget arm*-*-*]
} {
    set extra_flags ""
} else {
    set extra_flags "-fpic"
}
dg-runtest $srcdir/$subdir/981006-1.c "-Wuninitialized -O2 $extra_flags" ""
dg-finish

set lines [prune [split [prune_warnings [prune_gcc_output $lines]] "\n"] ""]

c-torture-execute $srcdir/$subdir/eeprof-1.c "-finstrument-functions"
