/*

   Copyright (C) 2007-2008 Free Software Foundation, Inc.
   Contributed by STMicroelectronics

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2, or (at your option) any later
version.

GCC is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING.  If not, write to the Free
Software Foundation, 51 Franklin Street, Fifth Floor, Boston, MA
02110-1301, USA.  */

#ifndef __LIBSTD_CONFNAME_H__
#define __LIBSTD_CONFNAME_H__

#ifndef __UNISTD_H && !defined __LIBSTD_CRT_BUILD
# error "Never use <bits/confname.h> directly; include <unistd.h> instead."
#endif

/* Remember to update values in src/MSCorlibWrapper.cs */

__BEGIN_EXTERN_C

enum {
  _SC_ARG_MAX                         = 0,
  _SC_CHILD_MAX                       = 1,
  _SC_CLK_TCK                         = 2,
  _SC_NGROUPS_MAX                     = 3,
  _SC_OPEN_MAX                        = 4,
  _SC_STREAM_MAX                      = 5,
  _SC_TZNAME_MAX                      = 6,
  _SC_JOB_CONTROL                     = 7,
  _SC_SAVED_IDS                       = 8,
  _SC_REALTIME_SIGNALS                = 9,
  _SC_PRIORITY_SCHEDULING             = 10,
  _SC_TIMERS                          = 11,
  _SC_ASYNCHRONOUS_IO                 = 12,
  _SC_PRIORITIZED_IO                  = 13,
  _SC_SYNCHRONIZED_IO                 = 14,
  _SC_FSYNC                           = 15,
  _SC_MAPPED_FILES                    = 16,
  _SC_MEMLOCK                         = 17,
  _SC_MEMLOCK_RANGE                   = 18,
  _SC_MEMORY_PROTECTION               = 19,
  _SC_MESSAGE_PASSING                 = 20,
  _SC_SEMAPHORES                      = 21,
  _SC_SHARED_MEMORY_OBJECTS           = 22,
  _SC_AIO_LISTIO_MAX                  = 23,
  _SC_AIO_MAX                         = 24,
  _SC_AIO_PRIO_DELTA_MAX              = 25,
  _SC_DELAYTIMER_MAX                  = 26,
  _SC_MQ_OPEN_MAX                     = 27,
  _SC_MQ_PRIO_MAX                     = 28,
  _SC_VERSION                         = 29,
  _SC_PAGESIZE                        = 30,
  _SC_RTSIG_MAX                       = 31,
  _SC_SEM_NSEMS_MAX                   = 32,
  _SC_SEM_VALUE_MAX                   = 33,
  _SC_SIGQUEUE_MAX                    = 34,
  _SC_TIMER_MAX                       = 35,
  _SC_BC_BASE_MAX                     = 36,
  _SC_BC_DIM_MAX                      = 37,
  _SC_BC_SCALE_MAX                    = 38,
  _SC_BC_STRING_MAX                   = 39,
  _SC_COLL_WEIGHTS_MAX                = 40,
  _SC_EQUIV_CLASS_MAX                 = 41,
  _SC_EXPR_NEST_MAX                   = 42,
  _SC_LINE_MAX                        = 43,
  _SC_RE_DUP_MAX                      = 44,
  _SC_CHARCLASS_NAME_MAX              = 45,
  _SC_2_VERSION                       = 46,
  _SC_2_C_BIND                        = 47,
  _SC_2_C_DEV                         = 48,
  _SC_2_FORT_DEV                      = 49,
  _SC_2_FORT_RUN                      = 50,
  _SC_2_SW_DEV                        = 51,
  _SC_2_LOCALEDEF                     = 52,
  _SC_PII                             = 53,
  _SC_PII_XTI                         = 54,
  _SC_PII_SOCKET                      = 55,
  _SC_PII_INTERNET                    = 56,
  _SC_PII_OSI                         = 57,
  _SC_POLL                            = 58,
  _SC_SELECT                          = 59,
  _SC_UIO_MAXIOV                      = 60,
  _SC_IOV_MAX                         = 61,
  _SC_PII_INTERNET_STREAM             = 62,
  _SC_PII_INTERNET_DGRAM              = 63,
  _SC_PII_OSI_COTS                    = 64,
  _SC_PII_OSI_CLTS                    = 65,
  _SC_PII_OSI_M                       = 66,
  _SC_T_IOV_MAX                       = 67,
  _SC_THREADS                         = 68,
  _SC_THREAD_SAFE_FUNCTIONS           = 69,
  _SC_GETGR_R_SIZE_MAX                = 70,
  _SC_GETPW_R_SIZE_MAX                = 71,
  _SC_LOGIN_NAME_MAX                  = 72,
  _SC_TTY_NAME_MAX                    = 73,
  _SC_THREAD_DESTRUCTOR_ITERATIONS    = 74,
  _SC_THREAD_KEYS_MAX                 = 75,
  _SC_THREAD_STACK_MIN                = 76,
  _SC_THREAD_THREADS_MAX              = 77,
  _SC_THREAD_ATTR_STACKADDR           = 78,
  _SC_THREAD_ATTR_STACKSIZE           = 79,
  _SC_THREAD_PRIORITY_SCHEDULING      = 80,
  _SC_THREAD_PRIO_INHERIT             = 81,
  _SC_THREAD_PRIO_PROTECT             = 82,
  _SC_THREAD_PROCESS_SHARED           = 83,
  _SC_NPROCESSORS_CONF                = 84,
  _SC_NPROCESSORS_ONLN                = 85,
  _SC_PHYS_PAGES                      = 86,
  _SC_AVPHYS_PAGES                    = 87,
  _SC_ATEXIT_MAX                      = 88,
  _SC_PASS_MAX                        = 89,
  _SC_XOPEN_VERSION                   = 90,
  _SC_XOPEN_XCU_VERSION               = 91,
  _SC_XOPEN_UNIX                      = 92,
  _SC_XOPEN_CRYPT                     = 93,
  _SC_XOPEN_ENH_I18N                  = 94,
  _SC_XOPEN_SHM                       = 95,
  _SC_2_CHAR_TERM                     = 96,
  _SC_2_C_VERSION                     = 97,
  _SC_2_UPE                           = 98,
  _SC_XOPEN_XPG2                      = 99,
  _SC_XOPEN_XPG3                      = 100,
  _SC_XOPEN_XPG4                      = 101,
  _SC_CHAR_BIT                        = 102,
  _SC_CHAR_MAX                        = 103,
  _SC_CHAR_MIN                        = 104,
  _SC_INT_MAX                         = 105,
  _SC_INT_MIN                         = 106,
  _SC_LONG_BIT                        = 107,
  _SC_WORD_BIT                        = 108,
  _SC_MB_LEN_MAX                      = 109,
  _SC_NZERO                           = 110,
  _SC_SSIZE_MAX                       = 111,
  _SC_SCHAR_MAX                       = 112,
  _SC_SCHAR_MIN                       = 113,
  _SC_SHRT_MAX                        = 114,
  _SC_SHRT_MIN                        = 115,
  _SC_UCHAR_MAX                       = 116,
  _SC_UINT_MAX                        = 117,
  _SC_ULONG_MAX                       = 118,
  _SC_USHRT_MAX                       = 119,
  _SC_NL_ARGMAX                       = 120,
  _SC_NL_LANGMAX                      = 121,
  _SC_NL_MSGMAX                       = 122,
  _SC_NL_NMAX                         = 123,
  _SC_NL_SETMAX                       = 124,
  _SC_NL_TEXTMAX                      = 125,
  _SC_XBS5_ILP32_OFF32                = 126,
  _SC_XBS5_ILP32_OFFBIG               = 127,
  _SC_XBS5_LP64_OFF64                 = 128,
  _SC_XBS5_LPBIG_OFFBIG               = 129,
  _SC_XOPEN_LEGACY                    = 130,
  _SC_XOPEN_REALTIME                  = 131,
  _SC_XOPEN_REALTIME_THREADS          = 132,
  _SC_ADVISORY_INFO                   = 133,
  _SC_BARRIERS                        = 134,
  _SC_BASE                            = 135,
  _SC_C_LANG_SUPPORT                  = 136,
  _SC_C_LANG_SUPPORT_R                = 137,
  _SC_CLOCK_SELECTION                 = 138,
  _SC_CPUTIME                         = 139,
  _SC_THREAD_CPUTIME                  = 140,
  _SC_DEVICE_IO                       = 141,
  _SC_DEVICE_SPECIFIC                 = 142,
  _SC_DEVICE_SPECIFIC_R               = 143,
  _SC_FD_MGMT                         = 144,
  _SC_FIFO                            = 145,
  _SC_PIPE                            = 146,
  _SC_FILE_ATTRIBUTES                 = 147,
  _SC_FILE_LOCKING                    = 148,
  _SC_FILE_SYSTEM                     = 149,
  _SC_MONOTONIC_CLOCK                 = 150,
  _SC_MULTI_PROCESS                   = 151,
  _SC_SINGLE_PROCESS                  = 152,
  _SC_NETWORKING                      = 153,
  _SC_READER_WRITER_LOCKS             = 154,
  _SC_SPIN_LOCKS                      = 155,
  _SC_REGEXP                          = 156,
  _SC_REGEX_VERSION                   = 157,
  _SC_SHELL                           = 158,
  _SC_SIGNALS                         = 159,
  _SC_SPAWN                           = 160,
  _SC_SPORADIC_SERVER                 = 161,
  _SC_THREAD_SPORADIC_SERVER          = 162,
  _SC_SYSTEM_DATABASE                 = 163,
  _SC_SYSTEM_DATABASE_R               = 164,
  _SC_TIMEOUTS                        = 165,
  _SC_TYPED_MEMORY_OBJECTS            = 166,
  _SC_USER_GROUPS                     = 167,
  _SC_USER_GROUPS_R                   = 168,
  _SC_2_PBS                           = 169,
  _SC_2_PBS_ACCOUNTING                = 170,
  _SC_2_PBS_LOCATE                    = 171,
  _SC_2_PBS_MESSAGE                   = 172,
  _SC_2_PBS_TRACK                     = 173,
  _SC_SYMLOOP_MAX                     = 174,
  _SC_STREAMS                         = 175,
  _SC_2_PBS_CHECKPOINT                = 176,
  _SC_V6_ILP32_OFF32                  = 177,
  _SC_V6_ILP32_OFFBIG                 = 178,
  _SC_V6_LP64_OFF64                   = 179,
  _SC_V6_LPBIG_OFFBIG                 = 180,
  _SC_HOST_NAME_MAX                   = 181,
  _SC_TRACE                           = 182,
  _SC_TRACE_EVENT_FILTER              = 183,
  _SC_TRACE_INHERIT                   = 184,
  _SC_TRACE_LOG                       = 185,
  _SC_LEVEL1_ICACHE_SIZE              = 186,
  _SC_LEVEL1_ICACHE_ASSOC             = 187,
  _SC_LEVEL1_ICACHE_LINESIZE          = 188,
  _SC_LEVEL1_DCACHE_SIZE              = 189,
  _SC_LEVEL1_DCACHE_ASSOC             = 190,
  _SC_LEVEL1_DCACHE_LINESIZE          = 191,
  _SC_LEVEL2_CACHE_SIZE               = 192,
  _SC_LEVEL2_CACHE_ASSOC              = 193,
  _SC_LEVEL2_CACHE_LINESIZE           = 194,
  _SC_LEVEL3_CACHE_SIZE               = 195,
  _SC_LEVEL3_CACHE_ASSOC              = 196,
  _SC_LEVEL3_CACHE_LINESIZE           = 197,
  _SC_LEVEL4_CACHE_SIZE               = 198,
  _SC_LEVEL4_CACHE_ASSOC              = 199,
  _SC_LEVEL4_CACHE_LINESIZE           = 200,
  _SC_IPV6                            = 236,
  _SC_RAW_SOCKETS                     = 237,
  _SC_V7_ILP32_OFF32                  = 238,
  _SC_V7_ILP32_OFFBIG                 = 239,
  _SC_V7_LP64_OFF64                   = 240,
  _SC_V7_LPBIG_OFFBIG                 = 241,
  _SC_SS_REPL_MAX                     = 242,
  _SC_TRACE_EVENT_NAME_MAX            = 243,
  _SC_TRACE_NAME_MAX                  = 244,
  _SC_TRACE_SYS_MAX                   = 245,
  _SC_TRACE_USER_EVENT_MAX            = 246,
  _SC_XOPEN_STREAMS                   = 247,
  _SC_THREAD_ROBUST_PRIO_INHERIT      = 248,
  _SC_THREAD_ROBUST_PRIO_PROTECT      = 249
};

__END_EXTERN_C

#endif 
