
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_rmi_rmic_RMIC$MethodRef__
#define __gnu_java_rmi_rmic_RMIC$MethodRef__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace rmi
      {
        namespace rmic
        {
            class RMIC$MethodRef;
        }
      }
    }
  }
}

class gnu::java::rmi::rmic::RMIC$MethodRef : public ::java::lang::Object
{

public: // actually package-private
  RMIC$MethodRef(::java::lang::reflect::Method *);
public:
  virtual jint compareTo(::java::lang::Object *);
  virtual jboolean isMatch(::java::lang::reflect::Method *);
private:
  static ::java::util::List * removeSubclasses(JArray< ::java::lang::Class * > *);
public:
  virtual void intersectExceptions(::java::lang::reflect::Method *);
public: // actually package-private
  ::java::lang::reflect::Method * __attribute__((aligned(__alignof__( ::java::lang::Object)))) meth;
  jlong hash;
  ::java::util::List * exceptions;
private:
  ::java::lang::String * sig;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_java_rmi_rmic_RMIC$MethodRef__
