
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_DefaultStyledDocument$ElementBuffer__
#define __javax_swing_text_DefaultStyledDocument$ElementBuffer__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
          class AbstractDocument$BranchElement;
          class AbstractDocument$DefaultDocumentEvent;
          class DefaultStyledDocument;
          class DefaultStyledDocument$ElementBuffer;
          class DefaultStyledDocument$ElementSpec;
          class Element;
      }
    }
  }
}

class javax::swing::text::DefaultStyledDocument$ElementBuffer : public ::java::lang::Object
{

public:
  DefaultStyledDocument$ElementBuffer(::javax::swing::text::DefaultStyledDocument *, ::javax::swing::text::Element *);
  virtual ::javax::swing::text::Element * getRootElement();
  virtual void remove(jint, jint, ::javax::swing::text::AbstractDocument$DefaultDocumentEvent *);
public: // actually protected
  virtual void removeUpdate();
  virtual void changeUpdate();
public:
  virtual void change(jint, jint, ::javax::swing::text::AbstractDocument$DefaultDocumentEvent *);
  virtual ::javax::swing::text::Element * clone(::javax::swing::text::Element *, ::javax::swing::text::Element *);
  virtual void insert(jint, jint, JArray< ::javax::swing::text::DefaultStyledDocument$ElementSpec * > *, ::javax::swing::text::AbstractDocument$DefaultDocumentEvent *);
public: // actually protected
  virtual void insertUpdate(JArray< ::javax::swing::text::DefaultStyledDocument$ElementSpec * > *);
private:
  ::javax::swing::text::Element * insertParagraph(::javax::swing::text::AbstractDocument$BranchElement *, jint);
  void insertFirstContentTag(JArray< ::javax::swing::text::DefaultStyledDocument$ElementSpec * > *);
  void insertContentTag(::javax::swing::text::DefaultStyledDocument$ElementSpec *);
  void createFracture(JArray< ::javax::swing::text::DefaultStyledDocument$ElementSpec * > *);
  void recreateLeaves(jint, ::javax::swing::text::AbstractDocument$BranchElement *, jboolean);
  JArray< ::javax::swing::text::Element * > * split(::javax::swing::text::Element *, jint, jint, jint);
  void insertFracture(::javax::swing::text::DefaultStyledDocument$ElementSpec *);
  JArray< ::javax::swing::text::Element * > * recreateAfterFracture(JArray< ::javax::swing::text::Element * > *, ::javax::swing::text::AbstractDocument$BranchElement *, jint, jint);
  static const jlong serialVersionUID = 1688745877691146623LL;
  ::javax::swing::text::Element * __attribute__((aligned(__alignof__( ::java::lang::Object)))) root;
  jint offset;
  jint endOffset;
  jint length;
  jint pos;
  ::javax::swing::text::Element * lastFractured;
  jboolean fracNotCreated;
  ::java::util::Stack * elementStack;
public: // actually package-private
  ::javax::swing::text::AbstractDocument$DefaultDocumentEvent * documentEvent;
  ::javax::swing::text::DefaultStyledDocument * this$0;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_swing_text_DefaultStyledDocument$ElementBuffer__
