
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_FlowView$LogicalView__
#define __javax_swing_text_FlowView$LogicalView__

#pragma interface

#include <javax/swing/text/BoxView.h>
extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
          class Element;
          class FlowView;
          class FlowView$LogicalView;
      }
    }
  }
}

class javax::swing::text::FlowView$LogicalView : public ::javax::swing::text::BoxView
{

public: // actually package-private
  FlowView$LogicalView(::javax::swing::text::FlowView *, ::javax::swing::text::Element *, jint);
  ::javax::swing::text::FlowView * __attribute__((aligned(__alignof__( ::javax::swing::text::BoxView)))) this$0;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_swing_text_FlowView$LogicalView__
