/* Map __<func>tf<n> to the name used for __float128.  */

#define __addtf3	__addjf3
#define __subtf3	__subjf3
#define __multf3	__muljf3
#define __divtf3	__divjf3
#define __eqtf2		__eqjf2
#define __netf2		__nejf2
#define __getf2		__gejf2
#define __gttf2		__gtjf2
#define __letf2		__lejf2
#define __lttf2		__ltjf2
#define __unordtf2	__unordjf2
#define __negtf2	__negjf2
#define __extenddftf2	__extenddfjf2
#define __extendsftf2	__extendsfjf2
#define __trunctfdf2	__truncjfdf2
#define __trunctfsf2	__truncjfsf2
#define __fixtfsi	__fixjfsi
#define __fixtfdi	__fixjfdi
#define __fixtfti	__fixjfti
#define __fixunstfsi	__fixunsjfsi
#define __fixunstfdi	__fixunsjfdi
#define __fixunstfti	__fixunsjfti
#define __floatsitf	__floatsijf
#define __floatditf	__floatdijf
#define __floattitf	__floattijf
#define __floatunsitf	__floatunsijf
#define __floatunditf	__floatundijf
#define __floatuntitf	__floatuntijf
