
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_awt_peer_gtk_GtkToolkit$LRUCache__
#define __gnu_java_awt_peer_gtk_GtkToolkit$LRUCache__

#pragma interface

#include <java/util/LinkedHashMap.h>
extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace awt
      {
        namespace peer
        {
          namespace gtk
          {
              class GtkToolkit;
              class GtkToolkit$LRUCache;
          }
        }
      }
    }
  }
}

class gnu::java::awt::peer::gtk::GtkToolkit$LRUCache : public ::java::util::LinkedHashMap
{

public:
  GtkToolkit$LRUCache(::gnu::java::awt::peer::gtk::GtkToolkit *, jint);
public: // actually protected
  virtual jboolean removeEldestEntry(::java::util::Map$Entry *);
public: // actually package-private
  jint __attribute__((aligned(__alignof__( ::java::util::LinkedHashMap)))) max_entries;
  ::gnu::java::awt::peer::gtk::GtkToolkit * this$0;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_java_awt_peer_gtk_GtkToolkit$LRUCache__
