
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_awt_peer_gtk_GtkChoicePeer__
#define __gnu_java_awt_peer_gtk_GtkChoicePeer__

#pragma interface

#include <gnu/java/awt/peer/gtk/GtkComponentPeer.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace awt
      {
        namespace peer
        {
          namespace gtk
          {
              class GtkChoicePeer;
          }
        }
      }
    }
  }
  namespace java
  {
    namespace awt
    {
        class Choice;
    }
  }
}

class gnu::java::awt::peer::gtk::GtkChoicePeer : public ::gnu::java::awt::peer::gtk::GtkComponentPeer
{

public:
  GtkChoicePeer(::java::awt::Choice *);
public: // actually package-private
  virtual void create();
  virtual void append(JArray< ::java::lang::String * > *);
  virtual jint nativeGetSelected();
  virtual void nativeAdd(::java::lang::String *, jint);
  virtual void nativeRemove(jint);
  virtual void nativeRemoveAll();
  virtual void connectSignals();
  virtual void selectNative(jint);
  virtual void selectNativeUnlocked(jint);
public:
  virtual void select(jint);
  virtual void add(::java::lang::String *, jint);
  virtual void remove(jint);
  virtual void removeAll();
  virtual void addItem(::java::lang::String *, jint);
public: // actually protected
  virtual void postChoiceItemEvent(::java::lang::String *, jint);
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_java_awt_peer_gtk_GtkChoicePeer__
